### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by hungnp194** [zinza-d2-training/anhlh-vue#1]
- Tìm hiểu về Typescript
  - [Spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) 
  - [Destructing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
  - [Object reference and cloning](https://javascript.info/object-copy)
  - [Default Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
  - [Interface/Type](https://www.typescriptlang.org/docs/handbook/2/objects.html)
  - [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)
  - [Class](https://www.typescriptlang.org/docs/handbook/2/classes.html)
  - Function type, arrow Func
  - [Advanced Type](https://www.typescriptlang.org/docs/handbook/utility-types.html)

- Bài tập
  - Clone object đã cho, sử dụng spread và destructing. Yêu cầu object và thuộc tính của object đã cloned không có reference tới object cũ [Link](https://codesandbox.io/s/spread-operator-destructing-object-cloning-rjmcy?file=/src/index.js)
  - Viết Model type cho các table database 

![covidtracker](https://user-images.githubusercontent.com/61738572/150733206-6ca87af2-86f0-464e-94b3-ef651c925930.png)

  - Sử dụng các advanced type để viết interface Scalars đại diện cho các kiểu dữ liệu của DB (Ví dụ: Int => number, varchar => string)
  - Sử dụng Scalars để thay thế các type cho model ở trên. Viết các type InsertInput (create api), SetInput (update api) kế thừa từ các model trên. (Ví dụ VaccineInsertInput, VaccineSetInput)

  - Mẫu đã làm [Link](https://www.typescriptlang.org/play#code/C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDsBXAG3IG4AoGgS2OAgCcAzOAY2gGVO5ycFgGcoAbxpQpUAJJMAXCVIBbZCwA0k6WkYhGwRWVWtN0qABEA9qUTkIhlWtPSAYuUtwDS4xq1SdyhDCwHDKYIrBLIwA5s5S5p4QwPSBEcBRxNF+eBAAHl6RMXFQAGpCnAAWQmkZsdkJzDVF2QH2UIWZNAC+dPqsHNx4KUEhYS70EOQAJqISZpwsEIlTAPqeinwCQsIA2gDkrcGhYHsAusWkYFPLa16bgiL7h6Mn5929TP1c0ADCi8sAVWErHGkxm4myCyWzFWiBAAH5FPAkKh7tt9nJgGcMMUoTc4StSMCWIjYAhkCggawce8GJ92N8oAAhODA0HTUR5ZjEcHPY7smbqKB-aEQKZUlgC2Y9OnMBmDMqcTiMaBciA80QstkTDkQsz0KYbfgPXZ7TFnYrEUJtNGPPZlFiVIQW7JwUjACqWKIALzFRq2dp0xD0TBdZjYLEsyjW0RtxvRZtDbzMwEsMYgpORFNtpvNpxpZmEnuAwn9JoxSeKRcsJZWU3oR2I3Ez5NR8bteYL0jYFHIIBWADcuMqrTCywm85oZaBIKVhyq5MTgHIwO6cFAAAr0TgAaxQipHECFewNe0IUD2VsCZ6IezdHq99F9UxvF4jUfTr72qc-5721ZLL8AOEOsGxCJsIC-HtKH7IclUYZY9gwWgZ2gA8VR4JIVzXXANyEZIBEpYlF1YZdiFXYAMA+OUBl+awmBYEAoDVDVmVZCApT1aQDXHDtK2yK84wDU0HSdFgw2kOCR08ehLGIUs53g0dZOIHZTlpVDhXo9IQBIlgyIo9ct13FAfm0xjj1PP9BKQlDwDo0gGJATCDJwzd8PoQizMcnS9NcyjqK+BV52UuTmPydVwS1DidXBOZuMNKAcwrLFk2kThzP7HikvbXN+LMKSELHHLhJSiSpGgvtBxC5ZeLy1LcUyxRvKcqc6E09DQuIPzsOAIztz3TqZLkyyXz-DKfMYlYrNvQrRzFKDe1gmqYVsmgOpWlSXN6oyPMIobkjknryPdKjZSC352PC7kovYzj4qkbLksTBrsmuRoSvLA5hiOMJyqgCanOmxLnsnSF2IU0H8ukKZoQqSHcrKtKpEBnTmsytr1vs4V2OOwzcIG0z2NGr93sg8bMuBr9+GBYRSbhunkKx2cfnY7aTr63C9vIIngTx07AvlaAJWuyLNTu2LZmyJ7EZe-62HoERgBWQS6v2USqnE5GoEEYIVetNX7XKTX-ogZQ4HochDY151tbAVlhAAdy9EHZZtrXMc0iV+c5zdCYlEm-wVpX9evP9deVmy-zNi3yC-e3hCdl21q94l2fx9z9M8nnvfk0jeqoqQgA)

**Comment by anhzinza** [comment]
1 .Spread syntax:
       -Spread là nói đến cách sử dụng dấu ‘…’
       -Khi sử spread trước mảng hoặc object  thì nó sẽ bỏ [] hoặc {}
          +vd: let a = […[1,2,3]] //[1,2,3]
                  let b = {…{a:’1’}}// {a:’1’}
2.Destructing
     - destructing giúp giải nén các giá trị hoặc thuộc tính từ mảng hoặc object
     - vd: let a = [10,20];
             let [b,c] = a;//b=10;c=20
3. object references and copying
    - tham trị  
      + kiểu  giá trị nguyên thuỷ:
           -string:đại diện cho dữ liệu văn bản
           -number:đại diện cho số;
           -Boolean : có giá trị true va false;
           -null: có giá trị null;
           -undefine: có giá trị là undefine và là giá trị mặc định của biến chưa được khởi tạo
          -symbol : đại diện cho 1 giá trị hằng số duy nhất
      + tham trị : đối với kiểu giá trị nguyên thuỷ thì khi gán giá trị thì nó sẽ lưu giá trị đó và tại thời điểm thì chỉ lưu 1 giá trị
         Vd: let a= ‘heloo’
                let b = a;
                a = ‘c’;// khi a thay đổi thì b ko thay đổi
    -Tham chiếu 
      +  Kiểu giá trị phức tạp : object,array,function
       + tham chiếu : đối với giá trị kiểu phức tạp khi gán giá trị cho nó thì nó sẽ lưu địa chỉ ô nhớ
            Vd: let a = [1,2,3];
                  let b = a;
                  a[0]=2;// khi đó giá trị của b = [2,2,3]
     -Compasion by references
            + 2 đối tượng bằng nhau nếu chúng là cùng 1 đối tượng nói cách khác là chúng phải cùng 1 lưu 1 địa chỉ
                  Vd : let a ={};
                         let b =a ;
                        console.log(a===b)//true
  -object.assign
             + object.assigin là copy tất cả các giá trị từ source sang target 
             + với thuộc tính của source là kiểu giá trị nguyên thuỷ thì sẽ copy theo kiểu tham trị ,còn đối với thuộc tính của source 
    là kiểu giá trị phức tạp thì sẽ copy theo kiểu tham chiếu 
            Vd1 : let a = [1,2,4];
                     let b = object.assign({},a);// b = [1,2,4]
           vd2 : let a= {class:{name:’lop1’}}
                    let b = object.assign({},a)
                    a.class.name = ‘lop2’;// b.class.name = lop2
4. data types
  - kiểu giá trị nguyên thuỷ:string,number,boolean
  - array có 2 kiểu kai báo
     +k1:  let a :number[] = [1,2,3];
     +k2: let a :Array<number> = [1,2,4];
  -any: là kiểu gán bất kỳ kiểu nào cho nó
       Vd : let a : any = {};
              let b : any = 1; 
  - void: là hàm sẽ ko trả về giá trị gì 
      Vd : function a( name:string):void{console.log(‘hello’)}
  -function : có thể định kiểu giá trị đầu vào và đầu ra  
       Vd: function a (name:string){
                  return ‘anh’  
                    }
      Vd: fucntion a (name:string): string{
                   return ‘anh’
              }
 -object types: Để liệt kê đối tượng thì cần liệt thuộc tính và kiểu của chúng
         Vd: function a(opt:{name:string}){}
             a({name:’123’})
        + optional properties : ta dùng ‘?’ để tuỳ chọn thuộc tính đó có hoặc ko
           Vd: function a(opt: {name:string,last?: string})
                   a({name:’anh’,last:’123’});
                   a({name:’anh’})
 -Unino types: sử dụng ‘|’ để cho biến đó có thể 1 hoặc nhiều kiểu khác 
           Vd: function a( id: string | number);
                               a(‘123’);
                               a(123);
 -Enum : khi kháo báo kiểu enum thì giá trị sẽ được đánh số tăng dần từ 0 
             Vd : enum Color{Red,Blue}
                   let a : Color = Color.Red;
                   console.log(a)//2
 -symbol : là giá trị nguyên thuỷ và tạo ra 1 tham chiếu duy nhất 
            Vd: let a = symbol(‘name’)
                   let b = symbol(‘name’)
                   console.log(a===b)//false
 5. types and interfaces
     -Types Aliases : mô tả dữ liệu trông như thế nào.
        Vd : type Year = number;
               let currentYear : Year = 2022;
    -Interfaces là đặt tên cho 1 kiểu đối tượng 
        Vd : interface Person{
           name: String 
           }
         function a (opt:Person){}
         a({name:’anh’})
    -So sánh types vs interfaces
           + interfaces merge được còn types thì ko
                Vd: interface Person{name:String}
                     interface Person {age:number} //Person{name:string,age:number}
             
          + interfaces có thể extend và implement  còn types thì ko:
               Vd: interface Person{name:String};
                      interface Student extend Person{lastname:String};

          + types và interfaces đều  có thể intersection
              Vd: type Name = {
                name: string
              };

              type Age = {
                age: number
                };

           type Person = Name & Age;
         
             Vd: interface Name = {name:String}
                   interface Age = {age:number}
                  type Person = Name & Age

**Comment by anhzinza** [comment]
6. generic
   - generic cho phép chuyền type components( function,class,interference) như 1 tham số.
         Vd: function dem<T> ( a:T) :T {
                  return a;
                  }
                dem<string>( ‘helo’);
  -Generic constraints
       Vd: function dem<T> (a:T):T{
            console.log(a.length)// báo lỗi thuộc tính length ko tồn tại trong kiểu Type
          }
    + để ngăn chặn điều này thì cần dùng extend 
Vd: interface lengthType { length : number}
       function dem<T extend lengthType> (a:T):T{
       console.log(a.length)// hết báo lỗi
       }
      dem(3) // báo lỗi 
      dem({length:2,a:3}// 2
7. class 
   - access modifilers:
       + public có thể truy cập được ở ngoài class
       + private chỉ truy cập được trong class
       + readonly có thể truy cập bên ngoài lớp ,chỉ đọc được và ko sửa được
       + proteced chỉ truy xuất được ở trong class và class kế thừa
-Kế thừa:
    + 1 lớp có thể kế thừa từ 1 lớp khác sử dụng extends
    + lớp con có thể kế thừa thuộc tính và phương thức của lớp cha nhưng giữ liệu được đánh dấu là private và constructor thì ko.
   +super() dùng để gọi constructor va thuộc tính, phương thức của lớp cha
-Phương thức ghi đè ( overriding) 
  + khi thuộc tính và phương thức của lớp cha bị trùng với lớp con thì sẽ bị lớp con ghi đè
-Static : thuộc tính và phương thức khi được đánh dấu bằng static thì ko cần dùng this và khởi tạo instance bằng biế new mà dùng trực tiếp tên class để truy xuất
-abstract class 
 +là class cha dùng cho tất cả các class có cùng bản chất( kiểu , loại ,nhiệm vụ)
 +các method ko chứa phần triển khai mà method ở class con sẽ làm nhiệm vụ triển khai
8 .Advanced type
-	Pick : để tạo ra 1 type mới từ type trc đó với 1 vài key cần thiết
-	Omit : tạo ra 1 type mới từ type trc đó và xoá key ko cần thiết từ type trc đó
-	Partial : tạo 1 type mới với thuộc tính của type trc đó và đặt ở chế độ tuỳ chọn.
-	Required : để tạo 1 type từ type trc đó và đặt ở chế độ bắt buộc

**Comment by anhzinza** [comment]
Bài tập : 
  bài 1: https://codesandbox.io/s/spread-operator-destructing-object-cloning-forked-t8wru1?file=/src/index.js
 bài 2: [link](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgMoLgGzlAzsgbwChlkBJcZALmRAFcBbAI2gBoTkAVUAT1DGq1GLKO1IA1HAgAWOQbjBRQAczFdgDCArgMADjQVKQqogF8iRftHhJ1m7XoBiwCJgAmhDgigQ4kNwD6foLoWDi4ANoA5Nz2YDq6UQC6anS6bn4QgcE0odh40bFa8XrJat6+-gFMPCEY+ZExGsUJyWYWluDWiCiSCAigWsgQAB6QIG74RQ66zq4exKTAbrn14dEUYMkA3BwgOhCrYQVRklAyOGUccHRg0gD2SgBeWTRoayfcIHzgV6QwUHuDCCykO72OjU2f2QYHuILB4IaG1+KQ4uAeYFwRyRUShqNI6PumICbmA2hASGx61xKLUMDomEwPACADdEAN9v4qSc8exzMgiGAeLpeuzBhRcNAwBRdLdkABeZAABWACAA1gAePocrSsZBRZZRZAAH31+00RtNURud0ewBebkt+oBQPhTqisLdJv1hMx7t9uBJZPiFIg7vpjOZbP6oEyjoAfLshSLkNrBqgINKQLKBIqlTgwMAsFqxSAIBKpTLbvGLFZYD1kABhe50cBQWqjcaTOwtJwudyLZDLbmQ2l7A5UPLUs4XKDQ6McvzAe4gQRpznLkARfHIDCSmiNuCS7ftQXClDN1uKHgVqBZnMK5WqzWXts8PUGx3eqLmsOJs8pq+14Zvecp5gWRaYBqQHtreoFgDWnSQPWtjrkuK7DGMEATPgPYzHM7ikIOSwrIi1K8hwpAIC2b4BMOTY0de0SGjupALrGXJkTyY6kP8DJMqypZxiOyJbKi5jJqKMYbiucFVrmT7qiW0noSAH6Gt+1FXu2dFfla7Gclk4b8VGQn+FE-6SamZmbiB8mPvmd6Qcpi6FrJICSne8k1nWNgXkeKCdth3bTCUsz9h4ni8UOpFTtxYlqKQGSQCJTRxK0rG7oxOn0TBPDMY6mV7loqUUdFbiVNIWJcaOCXtFZh6SnJ2ZgYpL4Bepen6slYaadlzIaVaxW4O6FV+FVFlJueTYBXZLUKY5hbFo15YeZW80+V0KEoAAqp5mFdlMzT4RFRGUTFpU8bxMDAHgYABL+qUzrIc6ZdgCgPRONXRM9lyZRADBwMAmBPVIL3QqQuhHrgADujyxR8jS-a9iXIAZqlrjZK7bqjBkldZ0laDj53FYIK3E9FWlvge-UnuYAG7Z5zUPnmz4antbD6oNzq3R9v7uu99389+ANA5g7pQ7gsPw5NDPIBzUBzSzyoQcWCvM9WQA)

**Comment by hungnp194** [comment]
@anhzinza Bài 1 em có thể làm ngắn gọn
```
const destructed = {
  ...country,
  status: {...country.status},
  vaccines: country.vaccines.map(vaccine => ({...vaccine}))
};
```
